name: Black Smith Photography
favicon: null
layout_spectrum: 0.8378750027623028
typography_spectrum: 0.4006746783852577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5903351064771414
  lightness: 0.24891676078550518
  saturation: 0.6181141487322748
  rhythmicContrast: 0.6660295007750392
purpose: []
